# Generated by Django 5.2 on 2026-06-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='crop_h',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='crop_w',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='crop_x',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='crop_y',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
