# Generated by Django 5.2 on 2026-06-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green')], default='black', max_length=20),
        ),
    ]
