# Generated by Django 5.2 on 2026-06-17 01:56

from django.db import migrations


class Migration(migrations.Migration):
    """
    Remove legacy models that moved to users / products / orders apps.

    Use SeparateDatabaseAndState because some databases were created without the
    Favourite unique_together constraint, which makes AlterUniqueTogether fail.
    """

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='favourite',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='favourite',
                    name='product',
                ),
                migrations.RemoveField(
                    model_name='favourite',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='order',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='userprofile',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='Product',
                ),
                migrations.DeleteModel(
                    name='Favourite',
                ),
                migrations.DeleteModel(
                    name='Order',
                ),
                migrations.DeleteModel(
                    name='UserProfile',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DROP TABLE IF EXISTS accounts_favourite CASCADE;
                        DROP TABLE IF EXISTS accounts_order CASCADE;
                        DROP TABLE IF EXISTS accounts_userprofile CASCADE;
                        DROP TABLE IF EXISTS accounts_product CASCADE;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
